apiVersion: v2
name: metrics-server
description: A Helm chart for metrics-server
type: application

version: 0.1.0
appVersion: "1.0"

dependencies:
- name: metrics-server
  version: '6.2.1'
  repository: https://charts.bitnami.com/bitnami
